# Generated by Django 3.1.1 on 2020-09-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigner', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=4)),
                ('desc', models.TextField()),
                ('dateon', models.DateField()),
                ('duedate', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
