# Generated by Django 3.1.1 on 2020-10-08 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
